------------------------------------------------------------
-- Tworzenie tabeli CINEMAS
------------------------------------------------------------
CREATE TABLE cinemas (
  cinema_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR2(100) NOT NULL,
  city        VARCHAR2(50)  NOT NULL,
  CONSTRAINT pk_cinemas PRIMARY KEY (cinema_id)
);

------------------------------------------------------------
-- Tworzenie tabeli MOVIES
------------------------------------------------------------
CREATE TABLE movies (
  movie_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  title       VARCHAR2(150) NOT NULL,
  duration    NUMBER        NOT NULL,
  CONSTRAINT pk_movies PRIMARY KEY (movie_id)
);

------------------------------------------------------------
-- Tworzenie tabeli HALLS
------------------------------------------------------------
CREATE TABLE halls (
  hall_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  cinema_id   NUMBER        NOT NULL,
  name        VARCHAR2(50)  NOT NULL,
  seats       NUMBER        NOT NULL,
  CONSTRAINT pk_halls PRIMARY KEY (hall_id),
  CONSTRAINT fk_halls_cinema
    FOREIGN KEY (cinema_id) REFERENCES cinemas(cinema_id)
);
------------------------------------------------------------
-- Tworzenie tabeli SEANCES
------------------------------------------------------------
CREATE TABLE seances (
  seance_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  movie_id    NUMBER       NOT NULL,
  hall_id     NUMBER       NOT NULL,
  seance_date DATE         NOT NULL,
  CONSTRAINT pk_seances PRIMARY KEY (seance_id),
  CONSTRAINT fk_seances_movie
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
  CONSTRAINT fk_seances_hall
    FOREIGN KEY (hall_id) REFERENCES halls(hall_id)
);

------------------------------------------------------------
-- Tworzenie tabeli CUSTOMERS
------------------------------------------------------------
CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name  VARCHAR2(50)  NOT NULL,
  last_name   VARCHAR2(50)  NOT NULL,
  email       VARCHAR2(100) NOT NULL,
  CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

------------------------------------------------------------
-- Tworzenie tabeli TICKETS
------------------------------------------------------------
CREATE TABLE tickets (
  ticket_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  seance_id   NUMBER NOT NULL,
  customer_id NUMBER NOT NULL,
  price       NUMBER(6,2) NOT NULL,
  sale_date   DATE DEFAULT SYSDATE,
  CONSTRAINT pk_tickets PRIMARY KEY (ticket_id),
  CONSTRAINT fk_tickets_seance
    FOREIGN KEY (seance_id) REFERENCES seances(seance_id),
  CONSTRAINT fk_tickets_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

------------------------------------------------------------
-- Tworzenie tabeli TICKETS_ARCHIVE
------------------------------------------------------------
CREATE TABLE tickets_archive (
  ticket_id   NUMBER,
  seance_id   NUMBER,
  customer_id NUMBER,
  price       NUMBER(6,2),
  sale_date   DATE,
  deleted_at  DATE
);
